apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
  # https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
            - name: status-port
              nodePort: 31619
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 30582
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 32441
              port: 443
              protocol: TCP
              targetPort: 8443
